version: 1
honeycomb_team: iteratest003-gettingstarted # the honeycomb team where queries for all deployment protection rules will run
deployment_protection_rules:
  Honey_test: # name of github environment where a deployment will occur
    queries:
      - honeycomb_environment: test # honeycomb environment where the query will run
        honeycomb_dataset: casabapentest2023_dataset123 # (optional) if not used, an environment-wide honeycomb query runs instead
        spec: '{
            "time_range": 7200,
            "calculations": [
                {
                    "o": "COUNT"
                }
            ],
            "filters": [
                {
                    "column": "duration_ms",
                    "op": "=",
                    "value": "500"
                },
                {
                    "column": "app.build_id",
                    "op": "=",
                    "value": "${GITHUB_RUN_ID}"
                }
            ],
            "filter_combination": "AND"
        }'
        threshold:
          operator: '>'
          value: 3
