version: 1

honeycomb_team: casabatest003-gettingstarted # the honeycomb team where queries for all deployment protection rules will run

deployment_protection_rules:
  Honey_test: # name of github environment where a deployment will occur
    queries:
      - honeycomb_environment: test # honeycomb environment where the query will run
        #honeycomb_dataset: my-cool-application # (optional) if not used, an environment-wide honeycomb query runs instead
        spec: queryspec '{
            "time_range": 7200,
            "granularity": 0,
            "breakdowns": [],
            "calculations": [
                {
                    "op": "COUNT"
                }
            ],
            "filters": [
                {
                    "column": "duration_ms",
                    "op": "=",
                    "value": "500"
                }
            ],
            "filter_combination": "AND",
            "orders": [],
            "havings": [],
            "limit": 1000
        }'
        threshold:
          operator: '>'
          value: 3
